name: pgw_sdk
description: PGWSDK for Flutter.
version: 0.0.3
homepage: https://github.com/2C2P/PGWSDK-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ccpp.pgw_sdk
        pluginClass: PgwSdkPlugin
      ios:
        pluginClass: PgwSdkPlugin
